
const CRIME_CLASSES_TO_CRIMES = {
  "THEFT": ["THEFT", "SHOPLIFTNG"],
  "TRAFFIC INCIDENT": ["VTOW", "VEH CODE", "PARK", "PURSUIT"],
  "FRAUD": ["IDENT THEF", "FRAUD"],
  "ASSAULT - OTHER": ["ASSAULT", "BATTERY", "CHILD ABUS"],
  "ALL OTHER - NON-CRIMINAL": ["MENTAL", "SUS CIRC", "ALAW", "CIV", "ACIT", "ACHP", "WELFAR CHK", "LOST", "FOUND", "MISS PERS", "OTHER", "AOTH", "TRESPASS", "ADEATH", "AFIRE", "BODY", "AMED", "UNSUB", "MCSO", "ANML", "MAST"],
  "ALL OTHER - CRIMINAL": ["WARR ARR", "TRO", "MISC PC", "THREATS", "DOM VIOL", "RESIST ARR", "MS", "EXPLODE", "ESCAPE", "BOMB"],
  "VANDALISM": ["VANDALISM"],
  "DRUGS / NARCOTICS VIOLATION": ["HS", "DRUGS", "DRUNK"],
  "WEAPONS VIOLATION": ["WEAPONS"],
  "SEXUAL OFFENSE - OTHER": ["SEX", "290", "INDEC EXPO"],
  "BURGLARY FROM MOTOR VEHICLE": ["BURG AUTO"],
  "ROBBERY - INDIVIDUAL": ["ROBBERY"],
  "MOTOR VEHICLE THEFT": ["VEH RECV"],
  "BURGLARY - RESIDENTIAL": ["BURG RES"],
  "BURGLARY - COMMERCIAL": ["BURG COMM"],
  "DISORDERLY CONDUCT": ["RUNAWAY", "DIST PEACE", "PROWLER"],
  "SEXUAL ASSAULT": ["RAPE"],
  "DEATH INVESTIGATION": ["SUICIDE"]
}

const getCrimes = async()=>{}